export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const CHANNEL_EXPIRED = 'CHANNEL_EXPIRED';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const CHANGE_NOTIFICATION = 'CHANGE_NOTIFICATION';
export const CHANNEL_USER_UPDATE = 'CHANNEL_USER_UPDATE';
export const CHANNEL_USER_SET = 'CHANNEL_USER_SET';
export const CHANNEL_EXTEND = 'CHANNEL_EXTEND';
export const CHANNEL_WILL_EXPIRE = 'CHANNEL_WILL_EXPIRE';
export const INIT_EXPIRE_STATE = 'INIT_EXPIRE_STATE';

export const UPDATE_CHANNEL_INFO = 'UPDATE_CHANNEL_INFO';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';
export const SET_UNREADCOUNT = "SET_UNREADCOUNT";
export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
export const LOAD_CHANNELS_FAIL = 'LOAD_CHANNELS_FAIL';
export const LOAD_MESSAGES_INIT = 'LOAD_MESSAGES_INIT';

export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';